# Generated by Django 4.2.7 on 2026-05-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_schoolasset_assetmaintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.classstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role_designation': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='finance.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('objectives', models.TextField(help_text='What will learners achieve by the end of this lesson?')),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('date_planned', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.classstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role_designation': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='finance.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('material_type', models.CharField(choices=[('NOTES', 'Revision Notes'), ('PAST_PAPER', 'Past Examination Paper'), ('SYLLABUS', 'Curriculum Syllabus Guide')], default='NOTES', max_length=15)),
                ('resource_url', models.URLField(help_text='Link to digital storage hosted notes or files (e.g., Google Drive/OneDrive)')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subject')),
            ],
        ),
    ]
