# Generated by Django 4.2.7 on 2026-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_feereceipt_date_issued_feereceipt_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.IntegerField(default=2026)),
            ],
            options={
                'ordering': ['level', 'term'],
                'unique_together': {('level', 'term', 'year')},
            },
        ),
    ]
