# Generated by Django 4.2.7 on 2026-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_feestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='term',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], default='TERM_1', max_length=10),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='payment_channel',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20),
        ),
    ]
