# Generated by Django 4.2.7 on 2026-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_feeinvoice_term_feeinvoice_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolannouncement',
            name='target_audience',
            field=models.CharField(choices=[('ALL_PARENTS', 'All Parents'), ('ALL_STUDENTS', 'All Students'), ('FORM_1', 'Form 1 Stream Blocks Only'), ('FORM_2', 'Form 2 Stream Blocks Only')], default='ALL_PARENTS', max_length=20),
        ),
    ]
