# Generated by Django 4.2.7 on 2026-06-07 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0007_timetableslot_lessonplan_learningmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK', 'Sick / Medical'), ('LEAVE', 'Authorized Leave')], default='PRESENT', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='finance.student')),
            ],
            options={
                'ordering': ['-date', 'student__admission_number'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
