# Generated by Django 4.2.7 on 2026-06-07 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_dailyattendancerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendancerecord',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.student'),
        ),
        migrations.RemoveField(
            model_name='dailyattendancerecord',
            name='notes',
        ),
    ]
